export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  tour: "/tour/:id",
  products: "/products",
  adminProducts: "/adminProd",
  adminExp: "/adminExp",
  adminCat: "/adminCat",
  adminAtt: "/adminAtt",
  adminCity: "/adminCiu",
  agregarC: "/nueva",
  agregarA: "/nuevoAtt",
  agregar: "/nuevo",
  agregarCity: "/nuevaCiu",
  category: "/products/:category",
  profile: "/profile",
  attribute: "/products/:attribute",
  dashboard: "/dashboard",
  emailConfirmation :"/bienvenido",
  reservation :"/reservation",
  reservationConfirm: "/confirmReserv",
  agregarP: "/nuevoPlace",
  adminPlace: "/adminPlace",
  misReservas: "/misReservas",
  resultSearch: "/results"
};
